### ISSUE TITLE
Responsive layout on dashboars

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#11]
Dashes should stay in one row next to each other as long as their total combined width is less than 100%.

Examples (one line is one row):

[dash 100]
[dash 100]
[dash 100]
[dash 1/2] [dash 1/2]
[dash 1/3] [dash 1/3] [dash 1/3]
[dash 1/6] [dash 1/6] [dash 1/3] [dash 1/3]
[dash 1/4] [dash 1/4] [dash 1/2] 

etc.

Each dash in one row shall have the same height.

**Comment by stefanscholz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboards](https://trello.com/c/1rD6oEiE/105-dashboards)

**Comment by stefanscholz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dash Sizes](https://trello.com/c/48V4OkKN/106-dash-sizes)

**Comment by moodledev** [comment]
![image](https://user-images.githubusercontent.com/46829091/71016201-6e044180-20ba-11ea-99c9-2f56abc58fbc.png)

It's working for me. Pull the lastest from local_dash and try again. Please send a screenshot of it not working as expected.

**Comment by stefanscholz** [comment]
Works for me (now), too :)
