### ISSUE TITLE
Dashboards: generic link

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#13]
If I try to access 

http://dash.bdecent.de/local/dash/dashboard.php (without ID), I get an error: A required parameter (id) was missing (which makes sense!).

If possible, instead direct the user to the first dashboard he has access to, and if he has access to no dashboard, direct the user to /my/

(the reason behind this would be to be able to add /local/dash/dashboard.php as a link to custommenu and/or boost's drawers, and therefor for managers or admins, get access to their specific dashboard, and for all other users, direct them to their usual "my" page.)

!!!!!LOW PRIORITY!!!!!

**Comment by stefanscholz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboards](https://trello.com/c/1rD6oEiE/105-dashboards)

**Comment by moodledev** [comment]
Please pull local_dash. If ID is not provided the first accessible dashboard will be displayed. If no dashboards are available for the user an error message will let them know.

**Comment by moodledev** [comment]
Okay now it will redirect to /my

**Comment by stefanscholz** [comment]
Ok
