### ISSUE TITLE
Dashboards stopped working after pulling new code

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#16]
When I access a previously working dashboard, I get this error now:

Exception - Class 'local_dash\block_manager' not found

**Comment by stefanscholz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboards](https://trello.com/c/1rD6oEiE/105-dashboards)

**Comment by moodledev** [comment]
Please pull latest from local_dash
