### ISSUE TITLE
Strings

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#17]
Just noticed strings in the local plugin, please add as always to main plugin (or is there a specific reason for having them in the local plugin?)

And why is Moodle 2 stable referenced here?

https://github.com/stefanscholz/moodle-local_dash/blob/f6eefecc7deba9fc8ae6bb957f9e41563933b043/lang/en/local_dash.php

**Comment by moodledev** [comment]
These are strings that must be in local_dash.php. Moodle has some conventions. The capabilities defined in the plugin will pull strings from only that plugin. Same for the subplugin names.

**Comment by moodledev** [comment]
I did remove the Moodle 2 reference and fixed the comments.

**Comment by stefanscholz** [comment]
Ok!
