### ISSUE TITLE
Dash configuration permissions

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#19]
Is it possible to remove the right to add a dash by default?

(currently, an editingteacher can add a dash, but cannot configure it and thus it "looks broken" or "not functional" – it would be better if somebody who cannot configure a dash can not even add it; this applies to all roles)

**Comment by stefanscholz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboards](https://trello.com/c/1rD6oEiE/105-dashboards)

**Comment by moodledev** [comment]
Should a non-editing teacher ever be able to add or change preferences on a dash block? They could theoretically access all data on the site.

**Comment by stefanscholz** [comment]
for now: creating dashes can be limited to admins (or managers? – what do you recommend?)
i.e. no, neither teacher nor editingteacher should be allowed to do that.

for the future (release 1.5 maybe): define for each data source, who has access, and maybe even define the scope of the datasource

**Comment by moodledev** [comment]
By default adding instances is now only allowed for managers and admins.

**Comment by stefanscholz** [comment]
the editingteacher can still add dashes on /my and in courses

<img width="1232" alt="Bildschirmfoto 2019-12-18 um 22 17 54" src="https://user-images.githubusercontent.com/3414705/71124059-54f7af80-21e4-11ea-93cb-04e892639a62.png">

<img width="1232" alt="Bildschirmfoto 2019-12-18 um 22 19 25" src="https://user-images.githubusercontent.com/3414705/71124116-75c00500-21e4-11ea-9b79-7eac16ad055f.png">

**Comment by stefanscholz** [comment]
(i've pulled a few min ago)

**Comment by stefanscholz** [comment]
does this maybe only take effect in anew install?

**Comment by moodledev** [comment]
Hmm this is interesting. Despite not having permission to add instances teachers can still add them. I'll do more digging

**Comment by stefanscholz** [comment]
That's weird indeed. But I just checked again, and it's definetively possible. The preferences button is gone, but configuration of dash block and adding of dash blocks is still possible.

**Comment by moodledev** [comment]
I changed the permissions. 'block/dash:myaddinstance' was inheriting from  'moodle/my:manageblocks' which was granting users the ability to add dash instances to their dashboard. Unfortunately upgrading the plugin won't adjust your roles, and you will have to uncheck 'block/dash:myaddinstance' for "authenticated users" role. I tested a new installation and only managers were able to add new dash instances.

**Comment by stefanscholz** [comment]
That seems to solve it partly; I can still though configure the block as teacher.
If I do that and change the source, I get the following error message, which are persistent, i.e. stay after page reload:
Notice: Undefined index: dd_link in /kunden/351761_83607/products/dash.bdecent.de/moodle/blocks/dash/classes/data_grid/data/data_collection.php on line 189

![image](https://user-images.githubusercontent.com/3414705/71932441-26944100-31a0-11ea-8469-ba14075aaeb4.png)

![image](https://user-images.githubusercontent.com/3414705/71932465-33189980-31a0-11ea-917a-601cf609b2b2.png)

If it is not possible to restrict the configuration, making the data source read only would do the job as well I think.

**Comment by stefanscholz** [comment]
If you say something like this won't happen on a fresh install, I can check that, just let me know.

**Comment by stefanscholz** [comment]
(I had changed the capability dash:myaddinstance for the auth. user to unset)

**Comment by moodledev** [comment]
Strange, I disallowed changing data source by making it read only when editing a block. That no longer seems to be the case. I will fix that.

As you probably have guessed, changing the data source causes too many problems. It's easier to simply delete the block and add a new one.

**Comment by moodledev** [comment]
Perhaps your teacher role has 'block/dash:myaddinstance' or 'block/dash:addinstance'? On a fresh install only a manager or admin will be able to add blocks.

**Comment by stefanscholz** [comment]
The data source is now locked. Will check on a fresh install to make sure, and will reopen this if necessary. Locking is a good idea to prevent abuse and undesired access to data sources.

**Comment by stefanscholz** [comment]
On my fresh install, the editing teacher was still able to both add and configure and set preferences for dash blocks.

**Comment by moodledev** [comment]
It was a similar issue. non-editing teacher have the 'block/dash:addinstance' permission by default. The change only worked on a fresh install. Existing Moodle will have to manually remove that permission.

**Comment by stefanscholz** [comment]
Just to make sure: you're saying that if I install dash for the first time on a fresh Moodle, the non editing teacher will not be able anymore by default to add dashes or access the preferences? Only managers and admins shall be able by default to add a dash anywhere in the site (that includes the dashboard)

**Comment by moodledev** [comment]
Yes, only managers and admins. I changed the permissions in the plugin but these don't take affect when upgrading. I tested a fresh install and the non-editing teacher could no longer add a dash on their dashboard.

**Comment by stefanscholz** [comment]
Perfect. I assume it's ok and will close this for now. Thx.
