### ISSUE TITLE
My participants / students does not work outside of course

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#2]
My participants / students condition only works in a course (but should work everywhere; if it's in a course, it should only show the current course participants, if it's not in a course, it should show all my participants from all courses). If it is easier, two separate  conditions are fine.

**Comment by moodledev** [comment]
I also added a "my groups" filter that doesn't take into consideration permissions, it may be useful if group members need to be displayed. Participants will display users the logged in user is "teaching". These may need more tweaking, please test

**Comment by stefanscholz** [comment]
OK (closing this one and using issue #3 for the remaining questions)
