### ISSUE TITLE
Dashboards data source: condition to hide public

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#20]
Can you add a condition like 

"Show only non-public dashboards"?

(I want to use public dashboards mostly for landing pages, thus they should not be listed in the dashboards data source; )

I.e. the conditions for the dashboards data source should ideally be (in addition to the default "all dashboards" when no condition is selected):

"My dashboards"
"Hide public dashboards"

**Comment by stefanscholz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboards](https://trello.com/c/1rD6oEiE/105-dashboards)

**Comment by moodledev** [comment]
I added the condition. pull the latest from both repos
