### ISSUE TITLE
Dashboards seem interconnected

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#26]
When I create a new dashboard, with a new name and a new shortname, it contains content from a dashboard I deleted. If I create another dashboard, it contains the same content and if I change content in the later dashboard, the first is changed as well... 

See video:
https://we.tl/t-4LrbRL4Jhl

**Comment by moodledev** [comment]
I changed how dashboards work that should fix the issue. Some blocks may be misplaced. If there's a block showing on all dashboards try deleting it and adding it to the correct dashboard. Obviously this won't be necessary for new installs, just old blocks that were added before the update.

**Comment by stefanscholz** [comment]
seems to work now. will repoen if I encounter problems.
