### ISSUE TITLE
users datasource: link href wrong

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#29]
Full name (linked to profile) links to http://dash.bdecent.de/user/profile.php?id=Demo%20User 
(i.e. to fullname instead of id)

**Comment by stefanscholz** [comment]
happens only in course I think, not on /my/

**Comment by stefanscholz** [comment]
<img width="2560" alt="Bildschirmfoto 2019-12-17 um 22 37 45" src="https://user-images.githubusercontent.com/3414705/71036381-ddf7e380-211d-11ea-8e73-c92a3bac8533.png">

**Comment by moodledev** [comment]
Is this still an issue? The links are working for me on the dashboard and courses. Is this a user data source?

**Comment by stefanscholz** [comment]
Yes, it's the users data source and it seems to only happen when it's in an accordion.

<img width="1106" alt="Bildschirmfoto 2019-12-18 um 23 18 18" src="https://user-images.githubusercontent.com/3414705/71128052-ae63dc80-21ec-11ea-8077-b76605dcb2a6.png">

**Comment by moodledev** [comment]
Can you try adding another block with the same configuration to the course and see if the issue persists in the new block?

**Comment by stefanscholz** [comment]
yes, it persists. (completely new block, with the users data source and the old accordion layout – it does not happen in the new accordion layout)

**Comment by moodledev** [comment]
I was able to reproduce and fix the issue on my dashboard. Please try it with your use case.

**Comment by stefanscholz** [comment]
confirmed :)
