### ISSUE TITLE
My participants / students does not consider groups

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#3]
If I am only the teacher in a certain group, it still shows participants of the whole course. It should instead show only the students in my groups. If there is a specific configuration required, please advise.

**Comment by moodledev** [comment]
Participants condition will now take into consideration per course permissions. Default teacher role seemed to be able to grade all users regardless of group membership. However, non-editing teacher can only grade users within their groups. (My knowledge on this is limited so maybe you are already aware of this)

**Comment by stefanscholz** [comment]
Can you please explain the difference between my groups and my students?

My groups contains only the students belonging to a group I belong to as a (non-editing)teacher, too?

My students contains all students of a course I teach, no matter in which group?

**Comment by moodledev** [comment]
**Participants condition** will filter results to users that I teach in any course (adheres to groups). The participants condition is used for teachers (or teacher-like roles) so they do not see any students outside their control (e.g. cannot grade). 

**My Groups** condition will filter results to users in my groups in any course. It's more generic. I can remove it if you want. Initially I had two conditions, My Groups and Enrolled users, but the overlap would exclude users without a group. So I left the My Groups condition because I can envision use cases. Example: My Classmates (?)

These conditions will benefit from the "current course" condition if you are adding a block to a specific course or course dashboard.

Thoughts?

**Comment by stefanscholz** [comment]
Sounds like a good idea. Is it possible to achieve the required dashes of the funding customer? 

https://trello.com/c/QXF0mBFi/76-initial-dashes-subplugin-or-just-custom

**Comment by moodledev** [comment]
Yes, I believe so.

"Show participants in this course in my group(s)"
"Show participants in all my courses where I am teacher "

Both of these conditions can be accomplished with the participants condition. The first scenario would also need the "Current course condition"

You can use the "My groups" condition if you only want to display users that are within a group (excluding enrolled users without a group membership). Really the My Groups condition is juat a modifier, you're mostly concerned with the participants condition.

Please let me know if the functionality should be different.

**Comment by stefanscholz** [comment]
What about the course and the group filter? 

And the fields Message link?

And the specified layout? (It's not a table which shall be shown in the accordion elements, see Google Doc)

And the icons?

I assume that this would be possible with a custom moustache template, but I cannot test that as that functionality is not yet available.

**Comment by moodledev** [comment]
I should have those fields and layout testable soon. I'm creating a new modified version of the accordion to achieve this. 

I'm thinking developing custom data sources will have the option to write custom mustache template, or choose from a standard layout.

**Comment by stefanscholz** [comment]
Great! I'm really keen on creating my own data sources using sql queries and learning moustache...

**Comment by moodledev** [comment]
Okay I created a new accordion layout. The old one is renamed as "Accordion layout (with tables)". Let me know if you have better names.

The new accordion layout has 4 additional fields to choose from. I added new message fields as well. In the Google doc you have an icon next to the bottom fields (days left in enrollment, and last login). Should these icons be configurable on the layout as well? Or would that be too cumbersome? The alternative is to create new fields of "days left in enrollment" and "last login" that contain icons.

![image](https://user-images.githubusercontent.com/46829091/71146193-e1f13780-21e9-11ea-822c-c5770ee52c46.png)

**Comment by stefanscholz** [comment]
The new layout is great, many thanks!

I don't like the idea to combine data (=field) with layout more than necessary. (the existing cases where a field is linked or has is a button make sense though) 

the most generic approach would be to allow a label and an icon for each field (in the new accordion and grid layout, not in table and the figure layouts). 

If that's too much effort (for this release), let's simply do it as a custom template; I assume it's pretty simple there.


I'll close this issue and move it to a new issue since it's essentially another topic.
