### ISSUE TITLE
Accordion layout icons

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#31]
...continued from the old issue...

The new layout is great, many thanks!

I don't like the idea to combine data (=field) with layout more than necessary. (the existing cases where a field is linked or has is a button make sense though) 

the most generic approach would be to allow a label and an icon for each field (in the new accordion and grid layout, not in table and the figure layouts). 

If that's too much effort (for this release), let's simply do it as a custom template; I assume it's pretty simple there.

**Comment by moodledev** [comment]
Sounds good. I need to figure out how to pull a list of available icons to display as options to the user. I'm thinking of a searchable select form field (since many icons exist).

**Comment by moodledev** [comment]
I believe we can only support font awesome icons. The standard icons do not compile a list in any way, but Moodle does store a mapping for font awesome. Is that okay? All newer themes should be using font awesome.

**Comment by stefanscholz** [comment]
Sure, that's fine!

**Comment by stefanscholz** [comment]
looks good!

(note to myself: change to icon grid in future release, sufficient for v1 for now)
