### ISSUE TITLE
Group filter

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#32]
still trying to produce the initial dashes and I think the group filter is missing? at least I can't find it.

if it's possible, maybe you can simply show it to me? I've created an admin account for you on my demo site.

**Comment by stefanscholz** [comment]
![image](https://user-images.githubusercontent.com/3414705/71177441-4f45ac80-226c-11ea-9c40-de0b59257638.png)

**Comment by stefanscholz** [comment]
(please ignore that it's a table layout, it should really be the accordion)

**Comment by moodledev** [comment]
I added a group filter to users and enrollments data source. Please test as a teacher (assuming you don't enroll your admin account in courses). The groups filter will show group options based on enrollment and permission. Unless you want admins to have all site groups as options?

**Comment by stefanscholz** [comment]
I'll test 👍 
No need to create exceptions for site admins. How do you query that though? (Any role that is assigned in a course that is not graded?)

**Comment by stefanscholz** [comment]
I mean does it work for an editing teacher, too? Or for a role that is built upon the teacher archetype?

**Comment by moodledev** [comment]
It uses the same logic as the My Groups condition. Loops through each enrolled course, return all groups if user has accessallgroups capability in that course, otherwise return user groups. Then it's simply an aggregation of all the groups from in each course.

**Comment by stefanscholz** [comment]
Perfect, sounds good.

**Comment by stefanscholz** [comment]
I will have to test this with more test cases to be sure it works as expected, it's not as easy to see if everything is correct. (And I am not so familiar with the groups as well unfortunately)

Is it technically possible to add a course filter to the enrollment data source? I assume it does not make sense for the users.

**Comment by moodledev** [comment]
"it's not as easy to see if everything is correct" is the theme of testing this thing in general. There is so much complexity and endless use cases. My effort is to create everything as flexible and simple as possible.

Yes, the course table is joined in the enrollments data source. I will add a course filter.

**Comment by stefanscholz** [comment]
That's so true and I appreciate the way you approach it!

Thx for the course filter!

**Comment by stefanscholz** [comment]
Group filter does not show all groups.

**Comment by stefanscholz** [comment]
![Screenshot_20191219_192645_com android chrome](https://user-images.githubusercontent.com/3414705/71199212-c04d8a00-2295-11ea-9e00-76984f73a769.jpg)

**Comment by moodledev** [comment]
Are you logged in as an admin? Do you have access to more groups?

**Comment by stefanscholz** [comment]
I was indeed. But something strange happens also when I login as teacher. 
I don't see any groups when I login as teacher (see attachment)

**Comment by stefanscholz** [comment]
![Screenshot_20191219_200114_com android chrome](https://user-images.githubusercontent.com/3414705/71201487-6bf8d900-229a-11ea-8cc1-8349c256e8fb.jpg)

**Comment by stefanscholz** [comment]
Oh, the screenshot does not show the contents of the filter (only "all groups" is in the filter)

**Comment by stefanscholz** [comment]
Here's a little more explanation for the group filter problem:

In my test scenario, I am non-editing teacher and member of two groups, a and b. Each group has students in them.  There's also a third group c, which the non-editing teacher is not a member of.

If it helps, let's have a call and we can go through it together?

<img width="835" alt="Bildschirmfoto 2020-01-06 um 16 11 44" src="https://user-images.githubusercontent.com/3414705/71826884-56a7eb00-309f-11ea-8091-82650eccb413.png">
<img width="846" alt="Bildschirmfoto 2020-01-06 um 16 11 36" src="https://user-images.githubusercontent.com/3414705/71826885-56a7eb00-309f-11ea-9e6c-d3ab8efd879b.png">
<img width="1274" alt="Bildschirmfoto 2020-01-06 um 16 11 25" src="https://user-images.githubusercontent.com/3414705/71826886-56a7eb00-309f-11ea-8083-3f72dd38bffb.png">
<img width="1589" alt="Bildschirmfoto 2020-01-06 um 16 12 56" src="https://user-images.githubusercontent.com/3414705/71826920-6b847e80-309f-11ea-801c-24fad3f871eb.png">

**Comment by stefanscholz** [comment]
In the screenshots, you can see several problems:

a) the non-editing teacher sees groups (in the group filter) which he is not part of
b) the group b is split into three accordion elements
c) there is no group d in that course

<img width="1976" alt="Bildschirmfoto 2020-01-06 um 16 15 15" src="https://user-images.githubusercontent.com/3414705/71827092-c322ea00-309f-11ea-9d33-589af8e963f3.png">

**Comment by moodledev** [comment]
The root problem with groups is that we are retrieving a master list of users, and trying to add group information. Here's a simple example of the issue. Consider this scenario:

User A (has the following groups):
-- Course 1: Group Foo
-- Course 2: Group Bar

When querying and grouping by user. Should the result set be

[User A, Course 1, Group Foo]
**OR**
[User A, Course 2, Group Bar]
**?**

MySQL makes the decision and also makes no promises. The user belongs in multiple groups, but we can only display one at a time. This problem causes confusing results when using the accordion layout. 

I noticed the users data source works really well if you use it in a course, limit it to the current course, and group by groups. Because the data source is no longer taking in groups from other courses.

I am not sure what the best solution is here. I am still thinking/testing...

**Comment by stefanscholz** [comment]
To answer your question: it should be both, i.e. if the user has two enrolments in two course, two rows would be my expected result.

User A, Course 1, Group Foo
User A, Course 2, Group Bar

Does that make sense?

**Comment by moodledev** [comment]
If you're okay with users being listed multiple times based on their groups then this will be greatly simplified (I think). This should mostly happen when a Dash is displaying site wide data. Within a course it won't be much of an issue.

**Comment by stefanscholz** [comment]
Sure, if a user is in several groups in a course, that's fine. I think that won't even happen that often. And if it does and it bothers a customer, we can always create a custom data source for that customer!

**Comment by stefanscholz** [comment]
Since we can't (or at least I don't want, even if we could) do something like a multi-level table with merged rows or something like that (at least for now), I don't see any other way to do that, it has to be several rows if a user has several groups (in one course). The only alternative would be to list several groups in the same column, coma separated. That would be fine, too, since the completion information would not be different depending on the group. Do what's easier!

**Comment by moodledev** [comment]
@stefanscholz Please try the user data source with the latest. I also added a new condition "current course groups". This will only return users that belong to a group in the current course. I ran into an issue where groups from other courses were bleeding over.

**Comment by stefanscholz** [comment]
I still see groups in the group filter which belong to another course. The data seems to be good though!

**Comment by moodledev** [comment]
Working on that now

**Comment by stefanscholz** [comment]
Great 😊

**Comment by moodledev** [comment]
Done. The group filter is now context sensitive. If the context is system or user (dashboard) the group filter will include all groups the user belongs to. If it's a course context the groups will be limited to the current course.

**Comment by stefanscholz** [comment]
👍👍👍
