### ISSUE TITLE
Adaptive/intelligent unique identifier for database records to prevent warnings

### ISSUE THREAD

**Issue by moodledev** [stefanscholz/moodle-block_dash#33]
Example: **Did you remember to make the first column something unique in your call to get_records? Duplicate value '24' found in column 'u_id'.**

**Comment by moodledev** [comment]
@stefanscholz With developer level debugging enabled, can you test your dashes to ensure no warnings are displayed?

**Comment by moodledev** [comment]
Hold on, the unique column is being displayed in tables, let me fix that first

**Comment by stefanscholz** [comment]
Sure, will test as soon as you say it's ready

**Comment by moodledev** [comment]
Ready

**Comment by stefanscholz** [comment]
Are you talking about standard dashes or custom ones?

**Comment by stefanscholz** [comment]
Are you talking about standard dashes or custom ones? @moodledev

**Comment by moodledev** [comment]
Any dashes. Turn on debugging and go to the dashboards, courses, etc. Let me know if you see any warnings.

**Comment by stefanscholz** [comment]
have not found any more warnings so far, will report them here once I find any.
