### ISSUE TITLE
Group Filter (users data source) + Accordion

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#34]
Using the old accordion layout and the users data source, I ses the groups (accordion headers) in a seemingly random order. Either order by alphabet or provide a setting.

![image](https://user-images.githubusercontent.com/3414705/71203795-fba08680-229e-11ea-81dc-e1892b35630a.png)

Prio B (can be releasae 1.1)

**Comment by moodledev** [comment]
@stefanscholz I added a default sorting field to the preferences modal. This will work for any data source / layout. And for tables it will sort by the default but obviously you can still click on the columns for sorting. Can we close this issue? The default sorting might not work properly with groups but that's a separate issue (the general pain groups is causing).

**Comment by stefanscholz** [comment]
Sure :) 
It always feels good to close issues.
