### ISSUE TITLE
Coding error when turning on editing mode after in empty, newly created dashboard "Course Completions" (coursecompletions)

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#44]
Error writing to database
Debug info: Data too long for column 'defaultregion' at row 1
INSERT INTO mdl_block_instances (blockname,parentcontextid,showinsubcontexts,pagetypepattern,subpagepattern,defaultregion,defaultweight,configdata,timecreated,timemodified) VALUES(?,?,?,?,?,?,?,?,?,?)
[array (
0 => 'dash',
1 => 1,
2 => 0,
3 => 'local-dash-dashboard-coursecompletions',
4 => NULL,
5 => 'coursecompletions',
6 => 0,
7 => '',
8 => 1576790727,
9 => 1576790727,
)]
Error code: dmlwriteexception
Stack trace:
line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown
line 1331 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
line 1377 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
line 817 of /lib/blocklib.php: call to mysqli_native_moodle_database->insert_record()
line 873 of /lib/blocklib.php: call to block_manager->add_block()
line 1472 of /lib/blocklib.php: call to block_manager->add_block_at_end_of_default_region()
line 1398 of /lib/blocklib.php: call to block_manager->process_url_add()
line 1500 of /lib/pagelib.php: call to block_manager->process_url_actions()
line 985 of /lib/pagelib.php: call to moodle_page->starting_output()
line 1299 of /lib/outputrenderers.php: call to moodle_page->set_state()
line 94 of /local/dash/dashboard.php: call to core_renderer->header()

**Comment by stefanscholz** [comment]
Note: "completions" works just fine, guess the name is too long?

**Comment by moodledev** [comment]
Block region names are limited to 16 characters in the database. I will need to limit the dashboard's shortname to 16 characters as well.

**Comment by moodledev** [comment]
Shortname is now limited to 16 characters. Please edit dashboard(s) that have long shortnames causing this error. This won't impact future dashboards.

**Comment by stefanscholz** [comment]
looks good now!
