### ISSUE TITLE
Debug messages in dashboard with dashes with data source course completions

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#46]
After adding another dash to the dashboard, this is shown:

Did you remember to make the first column something unique in your call to get_records? Duplicate value '0' found in column 'ccp_total_activities'.
line 1256 of /lib/dml/mysqli_native_moodle_database.php: call to debugging()
line 162 of /blocks/dash/classes/data_grid/sql_data_grid.php: call to mysqli_native_moodle_database->get_records_sql()
line 139 of /blocks/dash/classes/data_grid/sql_data_grid.php: call to block_dash\data_grid\sql_data_grid->get_records()
line 177 of /blocks/dash/classes/data_source/abstract_data_source.php: call to block_dash\data_grid\sql_data_grid->get_data()
line 213 of /blocks/dash/classes/layout/abstract_layout.php: call to block_dash\data_source\abstract_data_source->get_data()
line 243 of /blocks/dash/classes/data_source/abstract_data_source.php: call to block_dash\layout\abstract_layout->export_for_template()
line 125 of /blocks/dash/classes/output/renderer.php: call to block_dash\data_source\abstract_data_source->export_for_template()
line 73 of /blocks/dash/classes/block_builder.php: call to block_dash\output\renderer->render_data_source()
line 75 of /blocks/dash/block_dash.php: call to block_dash\block_builder->get_block_content()
line 336 of /blocks/moodleblock.class.php: call to block_dash->get_content()
line 230 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
line 1181 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1233 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 643 of /lib/outputrenderers.php: call to block_manager->ensure_content_created()
line 219 of /lib/mustache/src/Mustache/Context.php: call to core_renderer->standard_head_html()
line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
line 31 of data/localcache/mustache/1576769611/boost/__Mustache_e8d8ae873a984614cbb0bd0c2a191036.php: call to Mustache_Context->findDot()
line 13 of data/localcache/mustache/1576769611/boost/__Mustache_1c5088c2b2592d5b071229c5fbd20b21.php: call to __Mustache_e8d8ae873a984614cbb0bd0c2a191036->renderInternal()
line 67 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_1c5088c2b2592d5b071229c5fbd20b21->renderInternal()
line 195 of /lib/outputrenderers.php: call to Mustache_Template->render()
line 59 of /theme/boost/layout/columns2.php: call to renderer_base->render_from_template()
line 1374 of /lib/outputrenderers.php: call to include()
line 1304 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 94 of /local/dash/dashboard.php: call to core_renderer->header()
Did you remember to make the first column something unique in your call to get_records? Duplicate value '0' found in column 'ccp_total_activities'.
line 1256 of /lib/dml/mysqli_native_moodle_database.php: call to debugging()
line 162 of /blocks/dash/classes/data_grid/sql_data_grid.php: call to mysqli_native_moodle_database->get_records_sql()
line 139 of /blocks/dash/classes/data_grid/sql_data_grid.php: call to block_dash\data_grid\sql_data_grid->get_records()
line 177 of /blocks/dash/classes/data_source/abstract_data_source.php: call to block_dash\data_grid\sql_data_grid->get_data()
line 213 of /blocks/dash/classes/layout/abstract_layout.php: call to block_dash\data_source\abstract_data_source->get_data()
line 243 of /blocks/dash/classes/data_source/abstract_data_source.php: call to block_dash\layout\abstract_layout->export_for_template()
line 125 of /blocks/dash/classes/output/renderer.php: call to block_dash\data_source\abstract_data_source->export_for_template()
line 73 of /blocks/dash/classes/block_builder.php: call to block_dash\output\renderer->render_data_source()
line 75 of /blocks/dash/block_dash.php: call to block_dash\block_builder->get_block_content()
line 336 of /blocks/moodleblock.class.php: call to block_dash->get_content()
line 230 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
line 1181 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1233 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 643 of /lib/outputrenderers.php: call to block_manager->ensure_content_created()
line 219 of /lib/mustache/src/Mustache/Context.php: call to core_renderer->standard_head_html()
line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
line 31 of data/localcache/mustache/1576769611/boost/__Mustache_e8d8ae873a984614cbb0bd0c2a191036.php: call to Mustache_Context->findDot()
line 13 of data/localcache/mustache/1576769611/boost/__Mustache_1c5088c2b2592d5b071229c5fbd20b21.php: call to __Mustache_e8d8ae873a984614cbb0bd0c2a191036->renderInternal()
line 67 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_1c5088c2b2592d5b071229c5fbd20b21->renderInternal()
line 195 of /lib/outputrenderers.php: call to Mustache_Template->render()
line 59 of /theme/boost/layout/columns2.php: call to renderer_base->render_from_template()
line 1374 of /lib/outputrenderers.php: call to include()
line 1304 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 94 of /local/dash/dashboard.php: call to core_renderer->header()
Did you remember to make the first column something unique in your call to get_records? Duplicate value '0' found in column 'ccp_total_activities'.
line 1256 of /lib/dml/mysqli_native_moodle_database.php: call to debugging()
line 162 of /blocks/dash/classes/data_grid/sql_data_grid.php: call to mysqli_native_moodle_database->get_records_sql()
line 139 of /blocks/dash/classes/data_grid/sql_data_grid.php: call to block_dash\data_grid\sql_data_grid->get_records()
line 177 of /blocks/dash/classes/data_source/abstract_data_source.php: call to block_dash\data_grid\sql_data_grid->get_data()
line 213 of /blocks/dash/classes/layout/abstract_layout.php: call to block_dash\data_source\abstract_data_source->get_data()
line 243 of /blocks/dash/classes/data_source/abstract_data_source.php: call to block_dash\layout\abstract_layout->export_for_template()
line 125 of /blocks/dash/classes/output/renderer.php: call to block_dash\data_source\abstract_data_source->export_for_template()
line 73 of /blocks/dash/classes/block_builder.php: call to block_dash\output\renderer->render_data_source()
line 75 of /blocks/dash/block_dash.php: call to block_dash\block_builder->get_block_content()
line 336 of /blocks/moodleblock.class.php: call to block_dash->get_content()
line 230 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
line 1181 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1233 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 643 of /lib/outputrenderers.php: call to block_manager->ensure_content_created()
line 219 of /lib/mustache/src/Mustache/Context.php: call to core_renderer->standard_head_html()
line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
line 31 of data/localcache/mustache/1576769611/boost/__Mustache_e8d8ae873a984614cbb0bd0c2a191036.php: call to Mustache_Context->findDot()
line 13 of data/localcache/mustache/1576769611/boost/__Mustache_1c5088c2b2592d5b071229c5fbd20b21.php: call to __Mustache_e8d8ae873a984614cbb0bd0c2a191036->renderInternal()
line 67 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_1c5088c2b2592d5b071229c5fbd20b21->renderInternal()
line 195 of /lib/outputrenderers.php: call to Mustache_Template->render()
line 59 of /theme/boost/layout/columns2.php: call to renderer_base->render_from_template()
line 1374 of /lib/outputrenderers.php: call to include()
line 1304 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 94 of /local/dash/dashboard.php: call to core_renderer->header()
Did you remember to make the first column something unique in your call to get_records? Duplicate value '0' found in column 'ccp_total_activities'.
line 1256 of /lib/dml/mysqli_native_moodle_database.php: call to debugging()
line 162 of /blocks/dash/classes/data_grid/sql_data_grid.php: call to mysqli_native_moodle_database->get_records_sql()
line 139 of /blocks/dash/classes/data_grid/sql_data_grid.php: call to block_dash\data_grid\sql_data_grid->get_records()
line 177 of /blocks/dash/classes/data_source/abstract_data_source.php: call to block_dash\data_grid\sql_data_grid->get_data()
line 213 of /blocks/dash/classes/layout/abstract_layout.php: call to block_dash\data_source\abstract_data_source->get_data()
line 243 of /blocks/dash/classes/data_source/abstract_data_source.php: call to block_dash\layout\abstract_layout->export_for_template()
line 125 of /blocks/dash/classes/output/renderer.php: call to block_dash\data_source\abstract_data_source->export_for_template()
line 73 of /blocks/dash/classes/block_builder.php: call to block_dash\output\renderer->render_data_source()
line 75 of /blocks/dash/block_dash.php: call to block_dash\block_builder->get_block_content()
line 336 of /blocks/moodleblock.class.php: call to block_dash->get_content()
line 230 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
line 1181 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1233 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 643 of /lib/outputrenderers.php: call to block_manager->ensure_content_created()
line 219 of /lib/mustache/src/Mustache/Context.php: call to core_renderer->standard_head_html()
line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
line 31 of data/localcache/mustache/1576769611/boost/__Mustache_e8d8ae873a984614cbb0bd0c2a191036.php: call to Mustache_Context->findDot()
line 13 of data/localcache/mustache/1576769611/boost/__Mustache_1c5088c2b2592d5b071229c5fbd20b21.php: call to __Mustache_e8d8ae873a984614cbb0bd0c2a191036->renderInternal()
line 67 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_1c5088c2b2592d5b071229c5fbd20b21->renderInternal()
line 195 of /lib/outputrenderers.php: call to Mustache_Template->render()
line 59 of /theme/boost/layout/columns2.php: call to renderer_base->render_from_template()
line 1374 of /lib/outputrenderers.php: call to include()
line 1304 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 94 of /local/dash/dashboard.php: call to core_renderer->header()
Did you remember to make the first column something unique in your call to get_records? Duplicate value '1' found in column 'ccp_total_activities'.
line 1256 of /lib/dml/mysqli_native_moodle_database.php: call to debugging()
line 162 of /blocks/dash/classes/data_grid/sql_data_grid.php: call to mysqli_native_moodle_database->get_records_sql()
line 139 of /blocks/dash/classes/data_grid/sql_data_grid.php: call to block_dash\data_grid\sql_data_grid->get_records()
line 177 of /blocks/dash/classes/data_source/abstract_data_source.php: call to block_dash\data_grid\sql_data_grid->get_data()
line 213 of /blocks/dash/classes/layout/abstract_layout.php: call to block_dash\data_source\abstract_data_source->get_data()
line 243 of /blocks/dash/classes/data_source/abstract_data_source.php: call to block_dash\layout\abstract_layout->export_for_template()
line 125 of /blocks/dash/classes/output/renderer.php: call to block_dash\data_source\abstract_data_source->export_for_template()
line 73 of /blocks/dash/classes/block_builder.php: call to block_dash\output\renderer->render_data_source()
line 75 of /blocks/dash/block_dash.php: call to block_dash\block_builder->get_block_content()
line 336 of /blocks/moodleblock.class.php: call to block_dash->get_content()
line 230 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
line 1181 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1233 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 643 of /lib/outputrenderers.php: call to block_manager->ensure_content_created()
line 219 of /lib/mustache/src/Mustache/Context.php: call to core_renderer->standard_head_html()
line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
line 31 of data/localcache/mustache/1576769611/boost/__Mustache_e8d8ae873a984614cbb0bd0c2a191036.php: call to Mustache_Context->findDot()
line 13 of data/localcache/mustache/1576769611/boost/__Mustache_1c5088c2b2592d5b071229c5fbd20b21.php: call to __Mustache_e8d8ae873a984614cbb0bd0c2a191036->renderInternal()
line 67 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_1c5088c2b2592d5b071229c5fbd20b21->renderInternal()
line 195 of /lib/outputrenderers.php: call to Mustache_Template->render()
line 59 of /theme/boost/layout/columns2.php: call to renderer_base->render_from_template()
line 1374 of /lib/outputrenderers.php: call to include()
line 1304 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 94 of /local/dash/dashboard.php: call to core_renderer->header()

**Comment by moodledev** [comment]
A committed a fix for this on the day you posted the issue. There's a related github issue for tracking this. Please let me know if the issue persists.

**Comment by stefanscholz** [comment]
Looks good now with latest code.
