### ISSUE TITLE
Merge enrolments and completions  IMPORTANT! Please read first

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#47]
After looking at the enrolments and completions data sources, I am afraid that it would be better to have one combined data source instead of three separate ones. I have not put enough thought into "sources" originally, I just listed the variables and filters and really should have put them together in reasonable sources. You probably thought I did that with the context, but that was really only to explain where the field comes from, not about the source. Sorry for that.

What do you think about simplifying the sources as follows:
1) Users (no change)
2) Courses (no change)
3) Dashboards (no change)
4) Completion ("merged" from completions, enrolments and enrolment methods)

This would include the following fields:

**User Object** (same as in the existing enrolments, completions and users source)
**Course Object** (same as in the existing enrolments, completions and courses source)

**Enrolment**
- Enrolment Method Name
- Enrolment Method Status
- Enrollment start date
- Enrollment end date
- Days until start date
- Days until end date

**Course completion**
- Total activities (completion relevant)
- Completed activities
- Progress (Percentage of total vs. completed activities) NEW
- Course completed
- Date completed

**And the following filters:**
- Category
- Course start date
- Course end date
- Format
- Course tags
- Custom course fields
- Group
- Course
- Enrolment method
- Enrollment status
- Enrollment start date
- Enrollment end date

**And the following conditions:**
- Current course
- My groups
- Enrolment method = self NEW
- Enrolment method = not self NEW

**This data source would basically contain all users that are enrolled in a course and show their completion status in that course. Each row would be one user * course (=enrolment) combination. It can have information on the completion (if available), or not.**

I know that it's pretty late in the game to change/refine requirements; if you need more budget for this, let me know. I have the feeling however that fixing the issues with the three existing sources might take a while and effort, because they are not consistent – I mean they sometimes refer to a course, sometimes to a completion, sometimes to an enrolment instance, sometimes to an enrolment method. I want to avoid that you spend time and effort on fixing data sources, when it might be easier to create one. (especially because most of the fields, filters and conditions do already exist!)

Also, we'd have two sources less...

What are your thoughts?

**Comment by moodledev** [comment]
@stefanscholz I spent the majority of my time developing the inner workings of this plugin. "Data source" was my best solution to the problem of defining a container for the SQL query, available fields, filters, conditions, and preferences. Unfortunately, we can't have one big data source with all fields and filters available. For example, if you wanted to add logs to the mix, it would be too much in the query. And what if you want to start at the logs table?

We need a starting point [database table]. The joins in SQL are very important. Each data source has a starting table. Here's the completions SQL query template as an example: https://github.com/stefanscholz/moodle-local_dash/blob/master/classes/data_source/completions_data_source.php#L62
It starts with mdl_course_completion and joins in the necessary tables. The joins are very important and starting with a different table will yield different results.

If you have better ideas I am always open to new solutions.

I was able to merge the 3 data sources that you requested. From my limited testing, it seems to work fine. I will let you try it out before adding the new field and conditions. Any block using the old data sources will display an error.

**Comment by stefanscholz** [comment]
@moodledev  that's brilliant. I think it shows that the "engine" is well built if such an operation is easy to complete.

don't get me wrong please:
the setup you used (data sources, layouts, filters and conditions) is without doubt (imo) the best solution here. and – of course – we cannot have one big data source; I  have written many sql queries myself (struggled hard when I first tried to get this very query almost ten years with enrolled users and completion info) and therefor I do absolutely understand what you mean. 

I was never asking to merge more data sources, but I think merging those three is a pretty good solution and simplifies everything.

I will create a number of test dashes with it. What I can say already now is that the enrolment methods are not joined correctly; I get each row four times. maybe also a group issue.

I'll create separate issues for all problems I run into.

Regarding the comment above with the mdl_course_completion as a starting point: what if a course has no course completion enabled? (it is unlikely and I would even say it does not matter if a user who is enrolled in a course which has no course completion active is not shown in a "completion" data source)

Thank you!

**Comment by moodledev** [comment]
I understand you're not wanting one big source. I'm explaining my reasoning behind the data sources. Your last comment is a good example: if completion is not enabled for a course, enrollments from that course will not appear in the completion data source. This is because the source starts at mdl_course_completion and joins in the other tables. So that is one downside to merging 3 sources together. They did have independent uses. But you will know better about what is needed.

I will take a look at the joining issue with the new data source. Usually DISTINCT will take care of that, but something is causing duplicate records.

**Comment by stefanscholz** [comment]
You're right, there is always pros and cons. From past experience in customer projects, I have indeed had the impression that most customers have problems understanding when to use which source of there are similar ones available.

I assume we will sooner or later need a pure enrolment source again, but I feel more comfortable now with a simplified product. It's just release 1 after all! Pretty impressive for a first release I think what you've built!

**Comment by stefanscholz** [comment]
And I guess that creating an add-on with the enrolment source should be rather straight forward... I don't think it was wasted time at all, I just want to finish the release 1 👍

**Comment by stefanscholz** [comment]
The source works (almost) as expected; but it also has the problem of multiple entries. 

Example: the demo user has 6 entries for one course. Two for guest, two for self and two for manual enrolment. (in fact, the user is only self enrolled once; it does not matter if the enrolment fields are selected or nor btw)

**Comment by moodledev** [comment]
@stefanscholz Can you confirm this is still happening with the lastest?

**Comment by moodledev** [comment]
I'm having to add the enrollment fields as subqueries. The reason multiple records are returned is because I was joining enrollment methods table. And a course with multiple enrollment methods will return multiple records. It's the nature of the query. Grouping by the completion is one solution but has some downsides (e.g. you can't do a record count when grouping). I'll have something to test soon.

**Comment by stefanscholz** [comment]
Would it help if the enrolment methods are only used as filters?

**Comment by moodledev** [comment]
The complexity of the data source is making this difficult, but I have a solution that is not duplicating records for my courses (with multiple enrollment methods enabled). Please pull the lastest and try it with your Moodle.

**Comment by stefanscholz** [comment]
Looks good now. Can we do anything about the performance? It loads very slow (with about 1000 records, up to 30s...)

**Comment by stefanscholz** [comment]
Is the data source smart enough to query only the records the current user has access to (i.e. if "my students/participants" is chosen)? If it's only slow for admin users, I can live with that.

**Comment by stefanscholz** [comment]
Just tested it using "my groups" and it is now pretty fast again. I.e. all good.
Maybe we need to implement some caching method or maybe views in a future release... 
i.e. for this issue, the remaining tasks are adding:

Conditions:
- Enrolment method = self NEW
- Enrolment method = not self NEW

Field:
- Progress (Percentage of total vs. completed activities) NEW

Right?
Or am I missing something?

**Comment by stefanscholz** [comment]
two issues with the implementation:

wrong calculation/display of progress:
1 completed activity of 1 total completion relevant activity should be 100% (but is shown as 1%)
enrolment method still seems not to work properly: I have self enrolled, but it shows manual in the field see screenshot. I guess there's one row for each enrolment method in the background

(demo user 2 has self enrolled into that course)

<img width="1392" alt="Bildschirmfoto 2020-01-09 um 21 39 30" src="https://user-images.githubusercontent.com/3414705/72102990-89b0df80-3328-11ea-9ad7-9274219593af.png">
<img width="2560" alt="Bildschirmfoto 2020-01-09 um 21 44 33" src="https://user-images.githubusercontent.com/3414705/72103319-3f7c2e00-3329-11ea-92c0-913620350b06.png">

**Comment by moodledev** [comment]
The percentage is fixed.

I didn't think of this scenario (second screenshot). I have an easy solution, but with the solution comes a drawback. It would not display course completions that no longer have an enrollment. Will that be an issue? It's a consequence of merging everything together.

**Comment by stefanscholz** [comment]
That's ok. Am I right that you think about using user enrolments as base instead of completions?


For the future I suggest btw that we first build a SQL query and then create a data source once the query works exactly how it should be.

**Comment by moodledev** [comment]
We could use enrollments as the base, but I think we'd be better off restoring the user enrollments data source. The complication is the relationship between users and courses. You have to join the user enrollments, enrollment methods, and then the courses. Unfortunately there's no relationship between user enrollments and courses (without the intermediate enrollment methods table).

Should we close this issue?

**Comment by stefanscholz** [comment]
Your probably right, restoring the enrollments data source is a good idea; with that source, we can create a nice participants list. Is adding the condition (self enrolment / non self enrolment) there a quick thing?

Once you have applied your fix (i.e. no more wrong enrolment methods), the completion data source can then be closed. Let me know when I can test :)

**Comment by moodledev** [comment]
I misinterpreted your comment. I will update the query.

**Comment by moodledev** [comment]
You can now test the completions data source. If you want an enrollments/participants data source please create a separate issue.

**Comment by stefanscholz** [comment]
Finally 😊😊 Closing this now Thx for your patience!
