### ISSUE TITLE
Completions data source with new accoesion

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#48]
When I choose the new accordion layout with the completions data source, the following error message is displayed:

×
generalexceptionmessage
File: ...ayout/accordion_layout2.php
Line: 101
Stack trace:
Error code: generalexceptionmessage
* line 101 of /local/dash/classes/layout/accordion_layout2.php: Error thrown
* line 262 of /blocks/dash/classes/data_source/abstract_data_source.php: call to local_dash\layout\accordion_layout2->build_preferences_form()
* line 44 of /blocks/dash/classes/data_source/form/preferences_form.php: call to block_dash\data_source\abstract_data_source->build_preferences_form()
* line 214 of /lib/formslib.php: call to block_dash\data_source\form\preferences_form->definition()
* line 74 of /blocks/dash/lib.php: call to moodleform->__construct()
* line 7897 of /lib/moodlelib.php: call to block_dash_output_fragment_block_preferences_form()
* line 415 of /lib/external/externallib.php: call to component_callback()
* line 244 of /lib/externallib.php: call to core_external::get_fragment()
* line 79 of /lib/ajax/service.php: call to external_api::call_external_function()
generalexceptionmessage
File: ...ayout/accordion_layout2.php
Line: 101
Stack trace:
Error code: generalexceptionmessage
* line 101 of /local/dash/classes/layout/accordion_layout2.php: Error thrown
* line 262 of /blocks/dash/classes/data_source/abstract_data_source.php: call to local_dash\layout\accordion_layout2->build_preferences_form()
* line 44 of /blocks/dash/classes/data_source/form/preferences_form.php: call to block_dash\data_source\abstract_data_source->build_preferences_form()
* line 214 of /lib/formslib.php: call to block_dash\data_source\form\preferences_form->definition()
* line 74 of /blocks/dash/lib.php: call to moodleform->__construct()
* line 7897 of /lib/moodlelib.php: call to block_dash_output_fragment_block_preferences_form()
* line 415 of /lib/external/externallib.php: call to component_callback()
* line 244 of /lib/externallib.php: call to core_external::get_fragment()
* line 79 of /lib/ajax/service.php: call to external_api::call_external_function()

Error code: generalexceptionmessage
* line 101 of /local/dash/classes/layout/accordion_layout2.php: Error thrown
* line 262 of /blocks/dash/classes/data_source/abstract_data_source.php: call to local_dash\layout\accordion_layout2->build_preferences_form()
* line 44 of /blocks/dash/classes/data_source/form/preferences_form.php: call to block_dash\data_source\abstract_data_source->build_preferences_form()
* line 214 of /lib/formslib.php: call to block_dash\data_source\form\preferences_form->definition()
* line 74 of /blocks/dash/lib.php: call to moodleform->__construct()
* line 7897 of /lib/moodlelib.php: call to block_dash_output_fragment_block_preferences_form()
* line 415 of /lib/external/externallib.php: call to component_callback()
* line 244 of /lib/externallib.php: call to core_external::get_fragment()
* line 79 of /lib/ajax/service.php: call to external_api::call_external_function()

**Comment by moodledev** [comment]
Please try this again. I may have accidentally committed incomplete code.

**Comment by stefanscholz** [comment]
looks good now!
