### ISSUE TITLE
Public dashboards: content not displayed

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#49]
When I create a public dashboard, the content (i.e. the blocks) are not displayed memory size except for header

**Comment by moodledev** [comment]
![image](https://user-images.githubusercontent.com/46829091/71600626-77a79380-2b15-11ea-8f00-81a80fb6b7d0.png)

Public dashes work for me. Are you limiting data based on the logged in user? That won't work when there is no logged in user. Otherwise please send a screenshot of the preferences popup.

**Comment by stefanscholz** [comment]
Problem still exists, just pulled latest code. 
(block_dash 2019123001 and local_dash 2019123000)

http://dash.bdecent.de/local/dash/dashboard.php?id=18&edit=1

<img width="2560" alt="Bildschirmfoto 2019-12-30 um 23 32 31" src="https://user-images.githubusercontent.com/3414705/71603355-aac14580-2b5c-11ea-89bc-69dbbd68fae0.png">

**Comment by stefanscholz** [comment]
tried with the users and dashboards data source (with table layout) and only a category filter.

**Comment by moodledev** [comment]
This one is baffling me. Have you done anything advanced with permissions? Looks like your guest settings are the same as mine.

**Comment by stefanscholz** [comment]
Not that I'm aware of.

**Comment by stefanscholz** [comment]
The site is literally just for the plugin, except for the removal of the one capability which you told me to, no configurations have been made

**Comment by stefanscholz** [comment]
I can install a fresh Moodle 3.8 and see what happens

**Comment by stefanscholz** [comment]
In a fresh Moodle 3.8 install, dashboard contents are now visible. So this issue is resolved. However, as soon as I try to use a filter, I am sent to the login page. Should I create a new issue for that or do you want to keep this one for it?

**Comment by stefanscholz** [comment]
http://demo.bdecent.de/local/dash/dashboard.php?id=1

**Comment by moodledev** [comment]
I added a permission check to the filter submission. If the block lives in a public dashboard the filters can be submitted.
