### ISSUE TITLE
Group filter in completion data source shows duplication entries

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#50]
It lists each group (at least) 2 times. Using the filter then results in zero results with one of the group, and with the users (also duplicated) for the other group.

**Comment by moodledev** [comment]
Are you sure you don't have multiple groups with the same name?

**Comment by stefanscholz** [comment]
That's right, I do have multiple groups with the same name setup.
Can you please explain what the group filter does show? Probably I simply expected something else.

**Comment by moodledev** [comment]
@stefanscholz It's suppose to be a list of all groups the user has access to. Maybe it should be only the groups in the current context the user has access to?

**Comment by stefanscholz** [comment]
Yes, that's right, the context should matter (you were SOOO right about introducing the context for dashboards!! that's a brilliant feature):

If I am in a course (or on a dashboard in a course's context), it should only display the groups from that course.

if 
course 1 has groups a,b,c
course 2 has groups d,e,f
and the teacher1 is member of groups a,b and d,e

and "current course" is selected as condition

then
a dash on the course 2 page or a dashboard in course 2's context should show for teacher 1: 
in the group filter: d,e

a dash on a non-course related context should show for teacher 1: 
all groups the teacher has access to, i.e. a,b,d,e (not c and f)



Note 1
For a future release, i have already thought about a stronger effect of contexts. I.e. that a dash automatically takes the context as condition. that would make it possible that a teacher e.g. can add and configure dashes in a course, which would of course be a big advantage; but I had respect to anticipate all the consequences, which is why I think we should first specify this properly (and for now simply remove any rights to add and configure dashes to avoid that problem for now)

Note 2
In a future release, I want to have something like a "smart" dashboard, where you can select from all the courses which you have access to and it will automatically show the information for that course. a link to that dashboard, with the course preselected should be added to the course menu, probably to the drawer.

**Comment by stefanscholz** [comment]
Am I right that the "Current course" condition currently has no effect on the filters?
(i.e. it limits the data which is queried, but not the options in the filters?)

**Comment by stefanscholz** [comment]
The "current course" condition seems to have no effect on the users data source as well.
I have renamed all groups in order to see where they belong, i.e.

C1A, C1B, C1C all belong to Course 1
CSA, CSB, CSC all belong to Course S 
etc.

The screenshot was taken in Course S and to the right, you can see that no groups of that course are displayed. See the second screenshot for the participants view in that course.

<img width="1552" alt="Screenshot 2020-01-10 at 20 28 55" src="https://user-images.githubusercontent.com/3414705/72180640-dc9d9c00-33e7-11ea-811a-5f63c9ee28ac.png">

<img width="1552" alt="Screenshot 2020-01-10 at 20 30 58" src="https://user-images.githubusercontent.com/3414705/72180803-369e6180-33e8-11ea-8954-6ec6b23b53e0.png">

**Comment by moodledev** [comment]
@stefanscholz Is this resolved with the lastest updates?

**Comment by stefanscholz** [comment]
@moodledev this should now be fixed as well, right?

**Comment by moodledev** [comment]
I believe so

**Comment by stefanscholz** [comment]
👍
