### ISSUE TITLE
Renaming dashboard shortnames results in dashboard content gone

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#53]
If I change the shortname of a dashboard, the content of the dashbaord is gone; if I change it again to the original name, it's back there. Ideally, changing the shortname does not affect the content at all. 

Not critical for release 1.0, we can do that later if it's not an easy fix.

**Comment by moodledev** [comment]
What if the form doesn't allow changing of the shortname after creation of the dashboard? The shortname is only used for the block region name, it's just a unique identifier.

**Comment by stefanscholz** [comment]
That would be one option. 

If possible, I'd prefer something automatic in the background however, i.e. an unique identifier (just an iterating id maybe?) 

If it's only user internally, why provide the input in the first place?

**Comment by stefanscholz** [comment]
On the other hand, if we introduce pretty URLs in an upcoming release, maybe those shortnames come in handy?

**Comment by stefanscholz** [comment]
Probably you're right. Simply prevent a change after the dashboard has been created. We can figure it out later.

**Comment by moodledev** [comment]
Sounds good. I made the change
