### ISSUE TITLE
Exception - Class 'local_dash\data_grid\filter\current_course_condition' not found

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#57]
After installing a fresh moodle 3.8 and adding a dash to the moodle dashboard, I get the error message:

Exception - Class 'local_dash\data_grid\filter\current_course_condition' not found

**Comment by moodledev** [comment]
Please try again with the latest

**Comment by stefanscholz** [comment]
Fixed
