### ISSUE TITLE
Completion Data Source – Progress does not show correct value

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#59]
The completion data source shows a wrong percentage:

There are 10 required activites in the course; the user has completed two actvities, i.e. it should be 20%, instead, is shows 0%.

<img width="1552" alt="Screenshot 2020-01-10 at 19 35 11" src="https://user-images.githubusercontent.com/3414705/72177163-677a9880-33e0-11ea-86d5-4b30ca39bfd6.png">
:

<img width="386" alt="Screenshot 2020-01-10 at 19 35 57" src="https://user-images.githubusercontent.com/3414705/72177205-79f4d200-33e0-11ea-90a1-831120be4bfc.png">

**Comment by moodledev** [comment]
![image](https://user-images.githubusercontent.com/46829091/72179843-7004ac00-33ab-11ea-88b9-146da6fe05db.png)

It's working for me. Did it refresh?

**Comment by stefanscholz** [comment]
No, it did not. Do I need to run a specific cron job for the calculation?  I trigger the cron job every 5min.

**Comment by stefanscholz** [comment]
Oh, that's interesting: it says that there are 0 completion relevant activities in that course:

<img width="1552" alt="Screenshot 2020-01-10 at 20 41 31" src="https://user-images.githubusercontent.com/3414705/72181436-a103d180-33e9-11ea-93ce-b5f2dabbefb2.png">

Here's the completion criteria settings page:
<img width="1552" alt="Screenshot 2020-01-10 at 20 42 00" src="https://user-images.githubusercontent.com/3414705/72181456-acef9380-33e9-11ea-923b-9cc73662d727.png">

**Comment by stefanscholz** [comment]
Maybe that's related to the course being a "generated test course"?
(The "s" stands for a "s" course created by the make test course tool)

**Comment by moodledev** [comment]
Strange you and I would have different results with simple courses. I have changed how this data is queried. Please try it again.

**Comment by stefanscholz** [comment]
Now it works !
