### ISSUE TITLE
Groups field not showing any value

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#61]
Probably related to the other group issues, but for the sake of completeness: currently, in one of my test courses, the groups field does not show any value and using the group filter results in no entries, even though there should be plenty (as can be seen to the left). As condition, only "current course" has been selected.

Note: users used to be in two groups, maybe that's a reason for the issue. Users are now only in one group each, but the issue remains.

<img width="1552" alt="Screenshot 2020-01-10 at 20 14 04" src="https://user-images.githubusercontent.com/3414705/72179852-1ff70b00-33e6-11ea-8719-7d5ab3bd08a5.png">

**Comment by stefanscholz** [comment]
Note: this only happens in one course; from what I see, the main difference has been I have added the users via cohort sync and had assigned a group there; then I've deleted that group and instead manually created several groups.

**Comment by moodledev** [comment]
This may be resolved since I am grouping by users and groups now. Can you check if this issue persists?

**Comment by stefanscholz** [comment]
Yes 😊
