### ISSUE TITLE
users data source – groups...

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#62]
I just saw that now also in the users data source, there are multiple rows for each user, one for each group. I did not realize that your question apparently also applied to the users data source.

while it is perfectly fine for the completion data source (because users will usually only have one group per course) to have multiple entries, it really does not make sense for the users data source.

can you change the behavior of the users data source?
- ideally, it would be only one row if the group field is not shown, and several rows when the group field is not shown.
- if that is not possible, remove the group name field and group by user. (it should remain though as condition and filter in this case)
- or list the groups in the field comma separated (preferred)

i am sorry for my misinterpretation! :(

**Comment by moodledev** [comment]
I opted for "ideally, it would be only one row if the group field is not shown, and several rows when the group field is not shown."

When a group field is not enabled the data source will group by user.

**Comment by stefanscholz** [comment]
Perfect, thanks!
