### ISSUE TITLE
Coding error

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#64]
Class 'course_in_list' has been renamed for the autoloader and is now deprecated. Please use 'core_course_list_element' instead.
line 137 of /lib/classes/component.php: call to debugging()
line ? of unknownfile: call to core_component::classloader()
line 62 of /local/dash/classes/data_grid/field/attribute/course_image_url_attribute.php: call to spl_autoload_call()
line 49 of /local/dash/classes/data_grid/field/attribute/course_image_url_attribute.php: call to local_dash\data_grid\field\attribute\course_image_url_attribute::get_course_image()
line 105 of /blocks/dash/classes/data_grid/field/abstract_field_definition.php: call to local_dash\data_grid\field\attribute\course_image_url_attribute->transform_data()
line 65 of /blocks/dash/classes/data_grid/data/strategy/standard_strategy.php: call to block_dash\data_grid\field\abstract_field_definition->transform_data()
line 216 of /blocks/dash/classes/data_grid/sql_data_grid.php: call to block_dash\data_grid\data\strategy\standard_strategy->convert_records_to_data_collection()
line 212 of /blocks/dash/classes/data_source/abstract_data_source.php: call to block_dash\data_grid\sql_data_grid->get_data()
line 243 of /blocks/dash/classes/layout/abstract_layout.php: call to block_dash\data_source\abstract_data_source->get_data()
line 279 of /blocks/dash/classes/data_source/abstract_data_source.php: call to block_dash\layout\abstract_layout->export_for_template()
line 135 of /blocks/dash/classes/output/renderer.php: call to block_dash\data_source\abstract_data_source->export_for_template()
line 91 of /blocks/dash/classes/block_builder.php: call to block_dash\output\renderer->render_data_source()
line 112 of /blocks/dash/block_dash.php: call to block_dash\block_builder->get_block_content()
line 336 of /blocks/moodleblock.class.php: call to block_dash->get_content()
line 230 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
line 1181 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1233 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 643 of /lib/outputrenderers.php: call to block_manager->ensure_content_created()
line 219 of /lib/mustache/src/Mustache/Context.php: call to core_renderer->standard_head_html()
line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
line 31 of data/localcache/mustache/1580420685/boost/__Mustache_e8d8ae873a984614cbb0bd0c2a191036.php: call to Mustache_Context->findDot()
line 13 of data/localcache/mustache/1580420685/boost/__Mustache_0e1853b3568dc22a9821efe21a772dad.php: call to __Mustache_e8d8ae873a984614cbb0bd0c2a191036->renderInternal()
line 67 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_0e1853b3568dc22a9821efe21a772dad->renderInternal()
line 195 of /lib/outputrenderers.php: call to Mustache_Template->render()
line 59 of /theme/boost/layout/columns2.php: call to renderer_base->render_from_template()
line 1374 of /lib/outputrenderers.php: call to include()
line 1304 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 94 of /local/dash/dashboard.php: call to core_renderer->header()

Exception - Class 'local_dash\data_grid\field\attribute\moodle_url' not found
Debug info: 
Error code: generalexceptionmessage
Stack trace:
line 72 of /local/dash/classes/data_grid/field/attribute/course_image_url_attribute.php: Error thrown
line 49 of /local/dash/classes/data_grid/field/attribute/course_image_url_attribute.php: call to local_dash\data_grid\field\attribute\course_image_url_attribute::get_course_image()
line 105 of /blocks/dash/classes/data_grid/field/abstract_field_definition.php: call to local_dash\data_grid\field\attribute\course_image_url_attribute->transform_data()
line 65 of /blocks/dash/classes/data_grid/data/strategy/standard_strategy.php: call to block_dash\data_grid\field\abstract_field_definition->transform_data()
line 216 of /blocks/dash/classes/data_grid/sql_data_grid.php: call to block_dash\data_grid\data\strategy\standard_strategy->convert_records_to_data_collection()
line 212 of /blocks/dash/classes/data_source/abstract_data_source.php: call to block_dash\data_grid\sql_data_grid->get_data()
line 243 of /blocks/dash/classes/layout/abstract_layout.php: call to block_dash\data_source\abstract_data_source->get_data()
line 279 of /blocks/dash/classes/data_source/abstract_data_source.php: call to block_dash\layout\abstract_layout->export_for_template()
line 135 of /blocks/dash/classes/output/renderer.php: call to block_dash\data_source\abstract_data_source->export_for_template()
line 91 of /blocks/dash/classes/block_builder.php: call to block_dash\output\renderer->render_data_source()
line 112 of /blocks/dash/block_dash.php: call to block_dash\block_builder->get_block_content()
line 336 of /blocks/moodleblock.class.php: call to block_dash->get_content()
line 230 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
line 1181 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1233 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 643 of /lib/outputrenderers.php: call to block_manager->ensure_content_created()
line 219 of /lib/mustache/src/Mustache/Context.php: call to core_renderer->standard_head_html()
line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
line 31 of data/localcache/mustache/1580420685/boost/__Mustache_e8d8ae873a984614cbb0bd0c2a191036.php: call to Mustache_Context->findDot()
line 13 of data/localcache/mustache/1580420685/boost/__Mustache_0e1853b3568dc22a9821efe21a772dad.php: call to __Mustache_e8d8ae873a984614cbb0bd0c2a191036->renderInternal()
line 67 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_0e1853b3568dc22a9821efe21a772dad->renderInternal()
line 195 of /lib/outputrenderers.php: call to Mustache_Template->render()
line 59 of /theme/boost/layout/columns2.php: call to renderer_base->render_from_template()
line 1374 of /lib/outputrenderers.php: call to include()
line 1304 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 94 of /local/dash/dashboard.php: call to core_renderer->header()

**Comment by moodledev** [comment]
Did this error happen in Moodle or Totara?

**Comment by stefanscholz** [comment]
Moodle
When I create a dash with the course data source.

**Comment by moodledev** [comment]
Thanks. It should be fixed now

**Comment by stefanscholz** [comment]
Almost. New error message:
Shows up in the modal when opening the preferences:

<img width="891" alt="Bildschirmfoto 2020-01-31 um 21 34 28" src="https://user-images.githubusercontent.com/3414705/73572593-78637a80-4471-11ea-8664-9b68d0eeb2ec.png">


TypeError: Cannot read property 'get' of null
    at checkboxcontroller.replaceButton (https://demo.bdecent.de/theme/yui_combo.php?m/1580420685/form/checkboxcontroller/checkboxcontroller-debug.js:62:45)
    at checkboxcontroller.initializer (https://demo.bdecent.de/theme/yui_combo.php?m/1580420685/form/checkboxcontroller/checkboxcontroller-debug.js:51:21)
    at checkboxcontroller._initHierarchy (https://demo.bdecent.de/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:28941:33)
    at checkboxcontroller._baseInit (https://demo.bdecent.de/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:28508:18)
    at checkboxcontroller.init (https://demo.bdecent.de/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:29628:22)
    at checkboxcontroller._initBase (https://demo.bdecent.de/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:28472:23)
    at checkboxcontroller.BaseCore (https://demo.bdecent.de/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:28292:18)
    at checkboxcontroller.Base (https://demo.bdecent.de/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:29842:18)
    at new checkboxcontroller (https://demo.bdecent.de/theme/yui_combo.php?m/1580420685/form/checkboxcontroller/checkboxcontroller-debug.js:28:51)
    at Object.M.form.checkboxcontroller (https://demo.bdecent.de/theme/yui_combo.php?m/1580420685/form/checkboxcontroller/checkboxcontroller-debug.js:115:16)

**Comment by stefanscholz** [comment]
Update: does not show up anymore, I assume it was a temporary glitch. Will observe and reopen if required. Closing for now.
