### ISSUE TITLE
Coding error on totara using course data source

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#66]
Exception - Class 'local_dash\data_grid\field\attribute\moodle_url' not found
Debug info:
Error code: generalexceptionmessage
Stack trace:
line 72 of /local/dash/classes/data_grid/field/attribute/course_image_url_attribute.php: Error thrown
line 49 of /local/dash/classes/data_grid/field/attribute/course_image_url_attribute.php: call to local_dash\data_grid\field\attribute\course_image_url_attribute::get_course_image()
line 105 of /blocks/dash/classes/data_grid/field/abstract_field_definition.php: call to local_dash\data_grid\field\attribute\course_image_url_attribute->transform_data()
line 65 of /blocks/dash/classes/data_grid/data/strategy/standard_strategy.php: call to block_dash\data_grid\field\abstract_field_definition->transform_data()
line 216 of /blocks/dash/classes/data_grid/sql_data_grid.php: call to block_dash\data_grid\data\strategy\standard_strategy->convert_records_to_data_collection()
line 212 of /blocks/dash/classes/data_source/abstract_data_source.php: call to block_dash\data_grid\sql_data_grid->get_data()
line 243 of /blocks/dash/classes/layout/abstract_layout.php: call to block_dash\data_source\abstract_data_source->get_data()
line 279 of /blocks/dash/classes/data_source/abstract_data_source.php: call to block_dash\layout\abstract_layout->export_for_template()
line 135 of /blocks/dash/classes/output/renderer.php: call to block_dash\data_source\abstract_data_source->export_for_template()
line 91 of /blocks/dash/classes/block_builder.php: call to block_dash\output\renderer->render_data_source()
line 112 of /blocks/dash/block_dash.php: call to block_dash\block_builder->get_block_content()
line 340 of /blocks/moodleblock.class.php: call to block_dash->get_content()
line 266 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
line 1247 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1302 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 281 of /lib/outputrenderers.php: call to block_manager->ensure_content_created()
line 31 of /theme/basis/layout/partials/head.php: call to core_renderer->standard_head_html()
line 39 of /theme/basis/layout/default.php: call to require()
line 898 of /lib/outputrenderers.php: call to include()
line 828 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 252 of /course/view.php: call to core_renderer->header()

**Comment by moodledev** [comment]
Line 72 of [course_image_url_attribute.php](https://github.com/stefanscholz/moodle-local_dash/blob/master/classes/data_grid/field/attribute/course_image_url_attribute.php) no longer exists. Did you pull the latest from local_dash?

**Comment by stefanscholz** [comment]
I did; but I missed that there were merging errors; I resolved them, pulled again and now it seems to be fixed.
