### ISSUE TITLE
course summary and course summary files in course data source on totara

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#67]
course summary and course summary files field does not work

(add a course image and a course summary, create a dash and try to display image and/or summary, it will only show the placeholder image, not the configured image, the summary will not show as well)

<img width="2560" alt="Bildschirmfoto 2020-01-31 um 21 35 27" src="https://user-images.githubusercontent.com/3414705/73572665-a943af80-4471-11ea-88f0-6a8419edd83f.png">

**Comment by moodledev** [comment]
I fixed the course summary field. But the course summary files work for me.

![image](https://user-images.githubusercontent.com/46829091/73949087-88d78300-48bf-11ea-8ab5-7d414f1f107f.png)
