### ISSUE TITLE
Icons in accordion template are missing (in totara)

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#68]
<img width="728" alt="Bildschirmfoto 2020-01-31 um 22 03 16" src="https://user-images.githubusercontent.com/3414705/73574240-7d2a2d80-4475-11ea-89d7-045b56eba7ab.png">

**Comment by moodledev** [comment]
Looks like Totara doesn't have an icon system (and doesn't support font awesome). It uses old Moodle code where you have to specify a complonent (core, plugin, etc) and image name.

**Comment by moodledev** [comment]
I found this https://help.totaralearning.com/display/DEV/Flexible+Icons+API

**Comment by moodledev** [comment]
I'm going with the flex icons.
