### ISSUE TITLE
Multi select filters

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#7]
is there a good solution for multi selects? (the ones which you have used in repo are not suited for the front end i think, they are fine in the choose video modal, but would not want them on a dash)

**Comment by moodledev** [comment]
I'm open to suggestions. An HTML multiselect looks like this https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select_multiple

I agree that it would take up too much space.

**Comment by stefanscholz** [comment]
The one you suggested is perfect!

**Comment by moodledev** [comment]
My bad, I thought this was under release 1. I must have cleared the filter. But multiselect filters are now available

**Comment by stefanscholz** [comment]
This indeed surprised me :)  

But the one you implemented was the one which we agreed takes too much space; you had suggested another filter somewhere at that time (can't find it though anymore, do you recall what that suggestion was?), which looked a lot better.

**Comment by stefanscholz** [comment]
Maybe something like this?
https://select2.org/getting-started/installation
https://github.com/thdoan/pretty-dropdowns

**Comment by moodledev** [comment]
I didn't make a suggestion, I simply linked to this https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select_multiple

What about this? https://select2.org/getting-started/basic-usage#multi-select-boxes-pillbox

**Comment by moodledev** [comment]
Looks like we made the same suggestion 13 seconds apart. I can try select2

**Comment by stefanscholz** [comment]
Seems we have similar ideas :)

**Comment by stefanscholz** [comment]
Sure; but it's still not high priority; if you can finish the essential parts (most importantly getting the data and the groups right) in time (i.e. this week), multi select would be a great, too.
