### ISSUE TITLE
Content of public dashboard is not shown (on totara)

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#71]
<img width="2560" alt="Bildschirmfoto 2020-01-31 um 22 12 20" src="https://user-images.githubusercontent.com/3414705/73574744-c29b2a80-4476-11ea-937d-9819a80b7938.png">

**Comment by moodledev** [comment]
Totara (and perhaps Moodle) won't login visitors as guests unless guest access is enabled. Counterintuitively, this is done by showing the guest login button. 

Guests have the capability to view blocks.
