### ISSUE TITLE
Custom course fields do not show up in course data source (totara)

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#72]
<img width="2560" alt="Bildschirmfoto 2020-01-31 um 22 24 40" src="https://user-images.githubusercontent.com/3414705/73575441-7b159e00-4478-11ea-905c-9c5b95961711.png">

**Comment by moodledev** [comment]
I will need to learn the custom fields / reporting code in Totara. This is completely different from Moodle.

**Comment by moodledev** [comment]
Nevermind Totara implemented custom course fields separately.
