### ISSUE TITLE
Coding error after upgrading to latest version

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#73]
Capability "dashaddon/developer:managecustomlayouts" was not found! This has to be fixed in code.

line 453 of /lib/accesslib.php: call to debugging()

line 1304 of /lib/adminlib.php: call to has_capability()

line 4341 of /lib/navigationlib.php: call to admin_externalpage->check_access()

line 4373 of /lib/navigationlib.php: call to settings_navigation->load_administration_settings()

line 4373 of /lib/navigationlib.php: call to settings_navigation->load_administration_settings()

line 4373 of /lib/navigationlib.php: call to settings_navigation->load_administration_settings()

line 4324 of /lib/navigationlib.php: call to settings_navigation->load_administration_settings()

line 4179 of /lib/navigationlib.php: call to settings_navigation->load_administration_settings()

line 769 of /lib/pagelib.php: call to settings_navigation->initialise()

line 830 of /lib/pagelib.php: call to moodle_page->magic_get_settingsnav()

line 8319 of /lib/adminlib.php: call to moodle_page->__get()

line 19 of /admin/upgradesettings.php: call to admin_externalpage_setup()

Skip to main content

×This page should automatically redirect. If nothing is happening please use the continue link below.

(Continue)

Error output, so disabling automatic redirect.

**Comment by stefanscholz** [comment]
![Screenshot_20200206_014958_com android chrome](https://user-images.githubusercontent.com/3414705/73896501-78a1b280-4883-11ea-8954-6b8e2718ba40.jpg)
![Screenshot_20200206_015249_com android chrome](https://user-images.githubusercontent.com/3414705/73896505-79d2df80-4883-11ea-8c7a-b7f8d27202d6.jpg)

**Comment by moodledev** [comment]
Did you pull the latest of dashaddon_developer? The latest for all is
2020020500

Joe

**Comment by stefanscholz** [comment]
Just checked that. I had done a full git update, but it apparently did not update developer. Manually done that and now error is gone.
