### ISSUE TITLE
Class 'core_course\customfield\course_handler' not found

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#75]
Happens on Moodle 3.6.2 after configuring a dash.

Fehler: Class 'core_course\customfield\course_handler' not found
Debug info:
Error code: generalexceptionmessage
Stack trace:
line 212 of /local/dash/field_definitions.php: Error thrown
line 43 of /local/dash/lib.php: call to require()
line 61 of /blocks/dash/classes/data_grid/field/field_definition_factory.php: call to local_dash_register_field_definitions()
line 81 of /blocks/dash/classes/data_grid/field/field_definition_factory.php: call to block_dash\data_grid\field\field_definition_factory::get_field_definition_registry()
line 218 of /blocks/dash/classes/data_grid/field/field_definition_factory.php: call to block_dash\data_grid\field\field_definition_factory::get_all_field_definitions()
line 119 of /blocks/dash/classes/data_source/users_data_source.php: call to block_dash\data_grid\field\field_definition_factory::get_field_definitions_by_tables()
line 373 of /blocks/dash/classes/data_source/abstract_data_source.php: call to block_dash\data_source\users_data_source->build_available_field_definitions()
line 386 of /blocks/dash/classes/data_source/abstract_data_source.php: call to block_dash\data_source\abstract_data_source->get_available_field_definitions()
line 112 of /blocks/dash/classes/data_source/abstract_data_source.php: call to block_dash\data_source\abstract_data_source->get_sorted_field_definitions()
line 88 of /blocks/dash/classes/block_builder.php: call to block_dash\data_source\abstract_data_source->get_data_grid()
line 112 of /blocks/dash/block_dash.php: call to block_dash\block_builder->get_block_content()
line 321 of /blocks/moodleblock.class.php: call to block_dash->get_content()
line 230 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
line 1216 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1268 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 604 of /lib/outputrenderers.php: call to block_manager->ensure_content_created()
line 45 of /theme/mb2nl/renderers/core.php: call to core_renderer->standard_head_html()
line 45 of /theme/mb2nl/layout/parts/head.php: call to theme_mb2nl_core_renderer->standard_head_html()
line 107 of /theme/mb2nl/renderers/core.php: call to include()
line 83 of /theme/mb2nl/layout/columns3.php: call to theme_mb2nl_core_renderer->theme_part()
line 1328 of /lib/outputrenderers.php: call to include()
line 1258 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 244 of /course/view.php: call to core_renderer->header()

**Comment by stefanscholz** [comment]
Or is it an incompatibility with their theme? (they use a custom one)

**Comment by moodledev** [comment]
Moodle 3.6 does not support custom course fields (from what I can tell). Dash supports Moodle 3.7 and 3.8. But I have 2017051509 as the required version for Dash plugins so it installs on Totara. I can conditionally add custom course fields if the version of Moodle supports it. Otherwise they will not be available. Does that work for you?

**Comment by moodledev** [comment]
It says 3.7 in the docs https://docs.moodle.org/dev/Custom_fields_API

**Comment by stefanscholz** [comment]
Ah I see, that makes sense. Yes, that would be brilliant. Thanks!
