### ISSUE TITLE
Database error on PostgreSQL

### ISSUE THREAD

**Issue by mudrd8mz** [stefanscholz/moodle-block_dash#76]
The block shows the following error after being created:

Database error. The content cannot be displayed.

Error reading from database (ERROR: column "-" does not exist LINE 1: SELECT DISTINCT u.id || "-" || g.id as unique_id, u.id AS ... ^ SELECT DISTINCT u.id || "-" || g.id as unique_id, u.id AS u_id, g.id AS g_id, u.firstname AS u_firstname, u.lastname AS u_lastname, CONCAT(u.firstname, " ", u.lastname) AS u_fullname, CONCAT(u.firstname, " ", u.lastname) AS u_fullname_linked, u.email AS u_email, u.username AS u_username, u.idnumber AS u_idnumber, u.city AS u_city, u.country AS u_country, u.lastlogin AS u_lastlogin, u.department AS u_department, u.institution AS u_institution, u.address AS u_address, u.alternatename AS u_alternatename, u.firstaccess AS u_firstaccess, u.description AS u_description, u.id AS u_picture_url, u.id AS u_picture, u.id AS u_picture_linked, u.id AS u_profile_url, u.id AS u_profile_link, u.id AS u_message_url, u.id AS u_message_link, g.name AS g_name FROM m_user u LEFT JOIN m_user_enrolments ue ON ue.userid = u.id LEFT JOIN m_enrol e ON e.id = ue.enrolid LEFT JOIN m_course c ON c.id = e.courseid LEFT JOIN m_groups_members gm ON gm.userid = u.id LEFT JOIN m_groups g ON g.id = gm.groupid WHERE u.id = $1 AND u.id IN ($2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31) AND g.id = $32 AND c.id = $33 AND g.courseid = $34 GROUP BY u.id, g.id ORDER BY u.lastname ASC LIMIT 10

**Comment by mudrd8mz** [comment]
This is caused by using double quotes in places like
```
CONCAT(u.firstname, " ", u.lastname)
```

**Comment by mudrd8mz** [comment]
Please do not use hard-coded SQL functions like this. It only makes the plugin runnable on fewer sites. Please refer to https://docs.moodle.org/dev/Data_manipulation_API for methods like `sql_concat()`

**Comment by moodledev** [comment]
fixed
