### ISSUE TITLE
The namespacing levels guidelines are not follows

### ISSUE THREAD

**Issue by mudrd8mz** [stefanscholz/moodle-block_dash#78]
Please note there are rules on the names of the directories under the `classes` directory. Subspaces such as configuration, data_grid and others should be moved under the "local" namespace.

https://docs.moodle.org/dev/Coding_style#Namespaces

**Comment by moodledev** [comment]
@mudrd8mz Fixed. just curious... is there a technical reason for this guideline or just purely convention?

**Comment by mudrd8mz** [comment]
The technical reason is to avoid future collisions. The first-level subspace are also used by the core subsystems (such as privacy, task etc). So plugin authors can't put random things in there - they might get into conflict with a future core subsystem.

**Comment by moodledev** [comment]
thanks for the explanation
