### ISSUE TITLE
Remove course "1" from course data source

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#8]
In the data source, not only "real" courses, but also the site is listed. Please exlude it.

**Comment by stefanscholz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Data Source: Course](https://trello.com/c/VBOxJ1Sr/113-data-source-course)

**Comment by moodledev** [comment]
Please pull latest of local_dash

**Comment by stefanscholz** [comment]
ok
